### ISSUE TITLE
Crash on Android 4.4.4

### ISSUE THREAD

**Issue by yohpapa** [yohpapa/overlaymusicplayer#9]
I had the following feedback from a user.

> i've just installed "Overlay Music Player" from Play Store, but if i start the app, it crashes.
> My device is a Samsung Galaxy S3mini (I8190) with CM11 (4.4.4).
> 
> What can i do to get the music player work?

The problem happens on my device. My device is a Samsung Galaxy Nexus with AOKP (4.4.4).

**Comment by yohpapa** [comment]
The log when the problem happened is below:

> java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/genres from pid=14869, uid=10077 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
>   at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:467)
>   at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:394)
>   at android.content.ContentProvider$Transport.query(ContentProvider.java:194)
>   at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
>   at android.os.Binder.execTransact(Binder.java:404)
>   at dalvik.system.NativeStart.run(Native Method)
> FATAL EXCEPTION: AsyncTask #1
> Process: com.yohpapa.overlaymusicplayer, PID: 14869
> java.lang.RuntimeException: An error occured while executing doInBackground()
>   at android.os.AsyncTask$3.done(AsyncTask.java:300)
>   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
>   at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>   at java.lang.Thread.run(Thread.java:841)
> Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/genres from pid=14869, uid=10077 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
>   at android.os.Parcel.readException(Parcel.java:1465)
>   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
>   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
>   at android.content.ContentProviderProxy.query(ContentProviderNative.java:420)
>   at android.content.ContentResolver.query(ContentResolver.java:461)
>   at android.content.ContentResolver.query(ContentResolver.java:404)
>   at com.yohpapa.overlaymusicplayer.fragment.loader.GenreCursorLoader.loadInBackground(GenreCursorLoader.java:49)
>   at com.yohpapa.overlaymusicplayer.fragment.loader.SimpleCursorLoader.loadInBackground(SimpleCursorLoader.java:1)
>   at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
>   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
>   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
>   at android.os.AsyncTask$2.call(AsyncTask.java:288)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>   ... 3 more

The most important line is below:

> Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/genres from pid=14869, uid=10077 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

So I have to add android.permission.READ_EXTERNAL_STORAGE to my AndroidManifest.xml.
